### ISSUE TITLE
Orb in sample configs is out of date

### ISSUE THREAD

**Issue by Peeja** [CircleCI-Public/node-orb#114]
## Orb version:

N/A

## What happened:

I added a new project to CCI using the config builder. I couldn't figure out why it was behaving differently from what the documentation said—in particular, it wasn't installing the version of Node listed in my `.nvmrc`. Turns out it had given me `circleci/node@4.7`.

## Expected behavior:

Config builder should suggest `circleci/node@5` instead.

## Additional Information:

I know this isn't really a change to me made in this repo, but I'm not sure where else to file this. 😄

**Comment by Jaryt** [comment]
Looks like this updated on it's own. Possibly took a little bit of time for the orb registry to detect the changes 👍
