### ISSUE TITLE
Yarn installation fails if Yarn policies are in use

### ISSUE THREAD

**Issue by gggritso** [CircleCI-Public/node-orb#117]
## Orb version:

5.0.0

## What happened:

I'm using Yarn policies (e.g., `yarn policy set-version 1.22.11`) to bundle Yarn with my app. `.yarnrc` looks like this:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1579039968308
yarn-path ".yarn/releases/yarn-1.22.11.js"
```

I'm trying to use this orb to install  Node and Yarn, like so:

```yml
- node/install:
    install-yarn: true
```

This downloads the latest stable version of Yarn, which is `1.22.17` at the time of writing. Unfortunately, the installation process fails at the end with this error:

```
Verifying YARN install
Something went wrong; the specified version of Yarn could not be installed
```

This happens because after the Yarn installation is complete (`1.22.17` is successfully installed) `yarn --version` returns `1.22.11`, which is the version specified in `.yarnrc`. This mismatch causes the process to exit.

## Expected behavior:

I'm not sure, to be honest! A few options are possible:

- if the Yarn installation process somehow respected the contents of `.yarnrc` that would help
- if it was possible to skip the version check, that might be good
- if the installation check was smarter and checked policies that would help as well

I could hard-code the Yarn version in the task config, but that defeats the purpose of using `.yarnrc`. I could also somehow parse `.yarnrc` myself and extract the version, but that's the `yarn` executable's job. Any advice here would be appreciated!

**Comment by Jaryt** [comment]
Thanks! Will take a look into this and get back to you shortly 👍

**Comment by techpeace** [comment]
This was reported in the community forum, and I've also been running into it. [A user there reported that they tracked it down to a certificate check.](https://discuss.circleci.com/t/yarn-install-failing-node-orb/41477/2?u=techpeace)

**Comment by Jaryt** [comment]
Hi! After looking into this further, I'm wondering if installing yarn here is redundant as it looks like the `.yarn/releases` folder is allows yarn to be managed via source control. What behavior do you experience when you remove the `install-yarn` parameter?

**Comment by gggritso** [comment]
@Jaryt that's great, thank you!

**Comment by gggritso** [comment]
@Jaryt thank you very much for fixing this!
