### ISSUE TITLE
Orb behaviour with restore_cache does not match what source code says it should be doing

### ISSUE THREAD

**Issue by jamesrwu** [CircleCI-Public/node-orb#123]
## What happened:
In our node/install-packages step, I notice the restore_cache output to be something like this:

>No cache is found for key: node-deps-arch1-linux-amd64-6_85-v1-WEBPLAT-1424-otawg9WNM0SS_vutk39ZUPxQPgxUCFt5g4TXo9whdYs=
>Found a cache from build 188495 at node-deps-arch1-linux-amd64-6_85-v1-WEBPLAT-1424-3zVE04aLnLzo5ttkKIxeRB9NIhoXVIiqLiwkGMKBONA= 

After which `npm ci` runs for 5 minutes or so. After that is done, I notice that it is skipping cache generation with such a message

>Skipping cache generation, cache already exists for key: node-deps-arch1-linux-amd64-6_85-v1-WEBPLAT-1424-3zVE04aLnLzo5ttkKIxeRB9NIhoXVIiqLiwkGMKBONA=-otawg9WNM0SS_vutk39ZUPxQPgxUCFt5g4TXo9whdYs= 

## Expected behavior:

Based on the source code as I see here: https://github.com/CircleCI-Public/node-orb/blob/ccf5f1af8a1f226803fff4035aeb21ffaec6d23c/src/commands/install-packages.yml#L68-L72 My expectation 
is that during the cache restore step, it would have searched for the same cache key that  eventually got generated `npm ci` step.

## Additional Information:

Additional context from our config.yaml:
```orbs:
  node: circleci/node@5.0.0
```
We're running `node/install-packages` with no custom parameters.

**Comment by Jaryt** [comment]
Hi James! 

Thanks for bringing this up. Can you increment the cache-version parameter to "v2" and see if this behavior persists?

**Comment by nicklozon** [comment]
Ran into this too - the cache key when saving is not respecting the `cache-only-lockfile` parameter when set to true which is the default.

#129 attempts to solve the issue

**Workaround**: Set `cache-only-lockfile: false`
