### ISSUE TITLE
Allow LTS to be installed on Windows

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/node-orb#144]
## What happened:

When installing `lts` version of node on Windows, the message `Node.js v--lts.0.0 is only available in 32-bit.` will be output. `nvm install --lts` does not work with nvm on windows server.

## Expected behavior:

lts to install

## Additional Information:

Similar issue: https://github.com/ampproject/amphtml/issues/17538

**Comment by marboledacci** [comment]
The nvm for windows is different to the others, this is the one for windows https://github.com/coreybutler/nvm-windows. This orb doesn't support windows installation yet. You would have to manually install the windows version, and the you should be able to use the other commands of the orb.
