### ISSUE TITLE
ssh key issue with node/install

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/node-orb#152]
## Orb version:
5.0.2

## What happened:
When installing `git` before running `node/install` (in this case using self-hosted CircleCI runner), nvm will try to install via git, but then chokes / hangs on verifying the ssh key

```
=> Downloading nvm from git to '/home/circleci/.nvm'
=> Initialized empty Git repository in /home/circleci/.nvm/.git/
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

## Expected behavior:
`node/install` should be able to install nvm / node when git is installed.

**Comment by wyardley** [comment]
I am not sure what was happening, but it's not an issue for me now (other workaround), and the curl script used by the module _seems_ to work when I tested it on a couple of different images.

**Comment by Maxim-Filimonov** [comment]
> I am not sure what was happening, but it's not an issue for me now (other workaround), and the curl script used by the module _seems_ to work when I tested it on a couple of different images.

I have the same issue. Did you change anything to make it work?
