### ISSUE TITLE
Support pnpm 

### ISSUE THREAD

**Issue by imjared** [CircleCI-Public/node-orb#167]
## Describe Request:
pnpm seems to be chugging along nicely and found its footing as a stable package manager in the node/js ecosystem. It's especially helpful in monorepo setups. It'd be great to be able to leverage pnpm as a default in this orb. Anywhere that I can run commands via npm or yarn, I'd like to be able to run them via pnpm.

## Examples:
Ideally the `pkg-manager` option would allow for `pnpm` in addition to the existing enums. 

Related: #89

**Comment by pcfreak30** [comment]
I ran into this as well and might have to fork to support it.

**Comment by MikeMcC399** [comment]
- Link to PR #199

**Comment by marboledacci** [comment]
Pnpm support added in this version https://circleci.com/developer/orbs/orb/circleci/node?version=5.3.0#commands-install-pnpm
