### ISSUE TITLE
Prevent nvm from falling back to building from source

### ISSUE THREAD

**Issue by JamesHallowell** [CircleCI-Public/node-orb#183]
We've hit an issue that if the binary download fails, then nvm will [fall back to building Node from source](https://github.com/nvm-sh/nvm/blob/edacf8275e3bef4a80971625ed89df13a9af427c/nvm.sh#L2111). This takes a _long_ time and burns through credits, when it'd be quicker to just fail and try the job again.

nvm does support the [`-b` option for installs](https://github.com/nvm-sh/nvm/blob/edacf8275e3bef4a80971625ed89df13a9af427c/nvm.sh#L2845) so that it will only install from binary, and skip installing from source. It would be nice if this orb either set this option all the time, or provided some way to opt in to setting it.

Thanks!

**Comment by KyleTryon** [comment]
I'm tempted to set it all the time. I doubt anyone really wants to wait that long, if they did they would be far better off building their own image once.

Does anyone have any concerns? we'd probably have to make it a major change unfortunately.

**Comment by olleolleolle** [comment]
👋 Hi! We are in the same situation, and would like not to fall back either!

**Comment by olleolleolle** [comment]
👋 Here to say, HOORAY!
