### ISSUE TITLE
May need to be able to pass http session type to the curl commands

### ISSUE THREAD

**Issue by rit001** [CircleCI-Public/node-orb#193]
## Describe Request:

Someone has reported curl errors in the circleci forums here, when using the orb

https://discuss.circleci.com/t/nodejs-regularly-fails-to-install-after-10min/49170

The resulting curl errors seem to match reports like the following

https://stackoverflow.com/questions/56413290/getting-curl-92-http-2-stream-1-was-not-closed-cleanly-internal-error-err

This thread, while being rather old does indicate that the ability to switch curl back to the HTTP/1 protocol for HTTPS connections can resolve issues.

The ability to emulate the original poster's environment is limited due to a lack of info and the fact that I'm just helping out on the forums and so do not have easy access to all possible environments as I use a free circleci account.

**Comment by brainbicycle** [comment]
this is failing pretty often for us in this way: https://app.circleci.com/pipelines/github/artsy/eigen/47365/workflows/872ccd61-b83c-4450-a55a-c646145b060c/jobs/162183
May try installing via brew for now but any workarounds or ideas appreciated!

**Comment by marboledacci** [comment]
In version 6.2.0 the possibility to cache the nvm directories is added. We expect this to reduce significantly the error when installing node.
Also, the reported problems are coming in the nvm logic, so we cannot change the curl parameter for that.
I'm closing this, if the problem when installing node persist when using the cache, please create a new issue.
