### ISSUE TITLE
Latest container no longer includes `node-gyp`

### ISSUE THREAD

**Issue by jzempel** [CircleCI-Public/node-orb#195]
## Orb version:

5.1.0

## What happened:

From what I can tell, when `cimg/node:lts` advanced from `sha256:901508...` to `sha256:49c50d...` it seems `node-gyp` is no longer globally available. When this happens, `yarn install` short circuits and leaves builds in an unpredictable state. As one example, `yarn prepare` doesn't run.

It's hard to say, but this may be a combination particular to `lts` + `yarn` :shrug:

## Expected behavior:

Ideally, the container environment would remain stable within the context of an orb's major version.

## Additional Information:

Adding [yarn global add node-gyp](https://github.com/zendeskgarden/svg-icons/blob/2ef363ec5eab5b04de310de8cb37bb196d2bb9e5/.circleci/config.yml#L27) is getting our CI builds back on track.

**Comment by marboledacci** [comment]
Hello @jzempel, can you please provide more details about what you had and the error you got. Also, what was the equivalent version of the two lts you used.
