### ISSUE TITLE
Change `install-packages` `include-branch-in-cache-key` default to `false`

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/node-orb#197]
## Describe Request:

Today, the cache key for `install-packages` includes the branch name in the cache key by default: https://github.com/CircleCI-Public/node-orb/blob/ab05d0e3718e32232bdd9c80a8ba6fac1c0bee02/src/commands/install-packages.yml#L48-L52

This causes far more cache misses than necessary, IMO, especially because the lockfile hash is already included in the key.

I propose we change the default from `true` to `false` in the next major release. This will significantly improve user experience by reducing runtimes.

**Comment by ssunday** [comment]
Very much agree!

**Comment by Peter-Darton-i2** [comment]
I was really confused about why I wasn't getting any caching on each new PR until I found this.

If there are security concerns about cross-branch data leakage then they ought to be documented.
If not, the default should be changed.

**Comment by marboledacci** [comment]
There isn't any problem with changing the default to false for this. 
We have some changes to do for the cache on this orb, this included. But they are low priority for now as the same result can be obtain updating the parameters of the command.

**Comment by marboledacci** [comment]
This is now changed in version 7.0.0
