### ISSUE TITLE
The install command does not make global node or npm commands available

### ISSUE THREAD

**Issue by baronswindle** [CircleCI-Public/node-orb#3]
### Orb version
1.0.1

### What happened
The `install` command does not install `node` or `npm` into the `$PATH`. Consequently, downstream scripts that expect a global `node` or `npm` command will not work.

### Expected behavior
The `install` command should make global `node` and `npm` commands available to downstream scripts.

**Comment by iynere** [comment]
https://github.com/CircleCI-Public/node-orb/pull/6 closes this @baronswindle
