### ISSUE TITLE
Executor linting error

### ISSUE THREAD

**Issue by larsenwork** [CircleCI-Public/node-orb#33]
### Orb version

circleci/node@2.0.3

### What happened

When setting the executor and providing a name + tag as suggested in the docs: https://circleci.com/orbs/registry/orb/circleci/node#usage-run_tests_with_npm
```yml
jobs:
  test:
    executor:
      name: node/default
      tag: '13'
```

it doesn't lint (in VSCode): 
<img width="400" src="https://user-images.githubusercontent.com/3859425/80593310-44243980-8a21-11ea-9c24-228a48eff296.png">

### Expected behavior

That is lints nicely (the code works as expected). 

Other parts have nice intellisense such as when you hover over `executor`
<img width="400" src="https://user-images.githubusercontent.com/3859425/80593427-8188c700-8a21-11ea-80f4-93656d21b20f.png">

**Comment by KyleTryon** [comment]
Hello,

This is not an issue with the orb. The Json Schema needs to be updated: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/circleciconfig.json

This particular repo/project is not managed by us at CircleCI but we will do our best to submit a PR over to them.
