### ISSUE TITLE
"npm ci" cannot be executed

### ISSUE THREAD

**Issue by teppeis** [CircleCI-Public/node-orb#35]
### Orb version

2.1.0

### What happened

`node/install-packages` command executes:

- `npm install` by default
- `npm install` with `override-ci: false`
- `npm install` with `override-ci: true`

### Expected behavior

`node/install-packages` command should execute:

- `npm ci` by default
- `npm ci` with `override-ci: false`
- `npm install` with `override-ci: true`

From the description of `override-ci`:

> By default, modules will be installed with "npm ci" or "yarn install --frozen-lockfile", this override will use the standard "install" command.

Also the same problem occurs with yarn.

---

### Cause

The `if` statement is wrong.

https://github.com/CircleCI-Public/node-orb/blob/21cd04545bc827406e479915379b81e9104dad0c/src/commands/install-packages.yml#L64

It should be
```bash
if [[ << parameters.override-ci >> == true ]]; then
```
or
```bash
if << parameters.override-ci >>; then 
```
---

### Additional issue: cache

After solving the tiny bug above, the next problem is the cache.
Currently `node/install-packages` command caches/restores `node_modules` directory, but it doesn't work for `npm ci` because `npm ci` removes `node_modules` first.
So it should cache `~/.npm` for `npm ci` instead.

**Comment by KyleTryon** [comment]
Thank you for your help @teppeis,

Can you confirm if the latest patch release has resolved the issue?

Understanding the cache should still likely be an issue, we can address that next.

**Comment by KyleTryon** [comment]
I can take on the caching piece

**Comment by teppeis** [comment]
@KyleTryon Yes, I've confirmed that it has been modified to use `npm ci`. Thanks!

**Comment by KyleTryon** [comment]
Caching issues should be addressed here: https://github.com/CircleCI-Public/node-orb/pull/38

Please feel free to leave your thoughts.

**Comment by teppeis** [comment]
@KyleTryon Awesome improvement!

**Comment by KyleTryon** [comment]
Hello,

All Node version 3 has been released! Please let us know if you run into any issues.

Thank you!
