### ISSUE TITLE
app-dir default to working_directory

### ISSUE THREAD

**Issue by BrandonMathis** [CircleCI-Public/node-orb#42]
### Orb version
3.0.1

### What happened
Error on `node/install-packages`

```
---
Unable to find your package.json file. Did you forget to set the app-dir parameter?
---

Current directory: /home/circleci/project
```

### Expected behavior

I have `working_directory` set in my `.circleci/config.yml` and I feel that `app-dir` should default to that.

Thoughs? I would be willing to try my hand at a PR if this is even possible. Not sure CircleCI exposes the value of `working_directory` to orbs.

**Comment by felicianotech** [comment]
Interesting. There is an environment variable for `working_directory` called `$CIRCLE_WORKING_DIRECTORY`. There's a parameter type specifically for environment variables but the problem with that is then we HAVE to use one for this, which is a breaking change and less flexible.

Perhaps switching the default value to `app-dir` to an empty string would work. Then, if there's a non-empty string, it uses that path. If it's empty, then we use `$CIRCLE_WORKING_DIRECTORY`. @CircleCI-Public/cpeng Thoughts?

**Comment by gmemstr** [comment]
I think this is the best solution - looking into implementing this shortly.
