### ISSUE TITLE
Feat: ARM Support

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/node-orb#70]
## Describe Request:
Enable support for ARM-based installation and execution for CircleCI's upcoming ARM build fleet.

## Examples:
  - Install Node on ARM-based executor
  - Test all functionality

## Supporting Documentation Links:
CircleCI ARM build fleet: https://www2.circleci.com/arm.html

**Comment by gmemstr** [comment]
See #73 

There is some work we need to do for the machine image itself, specifically upgrading the `nvm` version.
