### ISSUE TITLE
Unable to cache based on `npm-shrinkwrap.json`...

### ISSUE THREAD

**Issue by busticated** [CircleCI-Public/node-orb#71]
## Orb version:

`circleci/node@4.1.0`

## What happened:

when your node project uses an `npm-shrinkwrap.json` file ([docs](https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json)), jobs fail to restore or save cache:

```
error computing cache key: template: cacheKey:1:30: executing "cacheKey" at <checksum "~/project/package-lock.json">: error calling checksum: open /home/circleci/project/package-lock.json: no such file or directory
```

## Expected behavior:

cache key should be calculated using either `package-lock.json` (as it does today) or `npm-shrinkwrap.json`

**Comment by gmemstr** [comment]
I wasn't aware `shrinkwrap` existed! As far as I can tell, it is most useful when locking dependencies for a module published to `npm`, and sees little use outside that. I am curious to know how widely this file is used nowadays so I can determine whether it's worth the effort of implementation (the effort is relatively low for naive approach, but we might need to reconsider how we do our caching parameters if we do opt to include this).

**Comment by busticated** [comment]
from the docs:

>npm-shrinkwrap.json is a file created by `npm shrinkwrap`. It is identical to `package-lock.json`, with one major caveat: Unlike `package-lock.json`, `npm-shrinkwrap.json` may be included when publishing a package.

this is key functionality when shipping more app-like things via `npm` - for example CLIs - as it ensures _exact_ dependencies are installed. i'm not aware of any plan to deprecate `npm shrinkwrap`

**Comment by gmemstr** [comment]
@busticated The newest version of the orb will now handle this use case, and is built in such a way that other package managers for Node that produce lockfiles should be easily supported. Thank you for raising this!
