### ISSUE TITLE
Add machine image tests

### ISSUE THREAD

**Issue by gmemstr** [CircleCI-Public/node-orb#78]
We encountered a bug with machine images resulting in new Node versions not being set while using `nvm`. This was addressed in #73, but we had to remove the machine image tests as the `nvm` version was for whatever reason incompatible with the commands we're running. These will need to be re-added once the next tag is released with the updated `nvm` command.

**Comment by Jaryt** [comment]
Will work on adding these back into the next major release. Thanks 👍
