### ISSUE TITLE
Docs don't explain how to install specific node version

### ISSUE THREAD

**Issue by shamilovtim** [CircleCI-Public/node-orb#97]
The docs state:

> Download and install any version of Node.js. Optionally installs Yarn with a parameter. You may use the default executor of this orb for a Node execution environment as well.

Yet no YML directive or API is documented for how to do this. This could use clarification as I don't quite understand what the docs are trying to say.

**Comment by Jaryt** [comment]
Good point! Added the usage to the installation example. This will be in #94 😄
